version: 3.0.0
schedule-options:
  memory-optimization: true
code-generation-options:
  debug-limit: 2
c-code-generation-options:
  c-optional-init-args:
  - int someVariable
  c-optional-execution-args:
  - int someVariable

